-- DO NOT EDIT THIS FILE DIRECTLY, instead: Create a file in this very same folder called config.lua, and override the values there. config.lua should automatically be created once you run the game with traitormod installed, but if you for some reason need to create it yourself, check out config.lua.example
-- Note: You can still edit this file directly, but using the above method is recommended so your configs are actually saved when you update this mod.

local config = {}
config.DebugLogs = true

----- USER FEEDBACK -----
config.Languages = {
    dofile(Traitormod.Path .. "/Lua/language/english.lua"), -- If it can't find a specific language key, it will always fallback to the first language on the list.
    dofile(Traitormod.Path .. "/Lua/language/russian.lua"),
}
config.Language = "Russian" -- English, Russian
config.SendWelcomeMessage = true
config.ChatMessageType = ChatMessageType.Private    -- Error = red | Private = green | Dead = blue | Radio = yellow

config.Extensions = {
    dofile(Traitormod.Path .. "/Lua/extensions/attackdefendreactorblastfix.lua"),
    dofile(Traitormod.Path .. "/Lua/extensions/servermessageutf8fix.lua"),
    --dofile(Traitormod.Path .. "/Lua/extensions/weaponnerfs.lua"),
    --dofile(Traitormod.Path .. "/Lua/extensions/paralysisnerf.lua"),
    --dofile(Traitormod.Path .. "/Lua/extensions/pressuremidjoin.lua"),
}

config.ExtensionConfig = {
    attackdefendreactorblastfix = {
        BlockedExplosives = {"fraggrenade", "40mmgrenade", "uex", "c4block_vipbombing", "ic4block", "40mmnuke", "alienartifactpiece", "arak_cinderblock3"},
        ProtectedGamemodes = {"AttackDefendV2"},
        ReactorTag = "deathmatchteam1reactor",
        ProtectTaggedReactorsOnly = true,
        Debug = false,
    }
}

----- DISCORD -----

config.Discord = {
    Enabled = true,
    DebugResponses = false,
    RoundCounterFile = Traitormod.Path .. "/Lua/data/roundcounter.json",
    StateFile = Traitormod.Path .. "/Lua/data/discordstate.json",

    Presence = {
        Enabled = true,
        Webhook = "",
        Username = "VoidTraitor Server",
    },

    Round = {
        Enabled = true,
        Webhook = "",
        Username = "VoidTraitor Round Logger",
    },

    Status = {
        Enabled = true,
        Webhook = "",
        MessageId = "",
        Username = "VoidTraitor Status",
        UpdateInterval = 15,
        AutoCreateMessageIfMissing = true,
        AutoSaveMessageId = true,
        EmbedColor = 16753920,
        FooterText = "VoidTraitor",
        ShowNextRoundInLobby = true,
        ShowModeField = true,
        ShowMapField = true,
        ShowSubmarineField = true,
    },

    Logs = {
        Enabled = false,
        Webhook = "",
        Username = "Server Logs",
        FlushInterval = 1,
        MaxMessagesPerBatch = 15,
        MaxPayloadLength = 1800,
    },
}

config.DiscordWebhookConfig = nil -- legacy compatibility for old webhook-only configs

----- GAMEVOTE -----

config.GameVote = {
    DurationSeconds = 30,

    Modes = {
        {
            Name = "Secret",
            LanguageKey = "GameVoteOptionSecret",
            Apply = "Secret"
        },
        {
            Name = "AttackDefend",
            LanguageKey = "GameVoteOptionAttackDefend",
            Apply = "AttackDefend"
        },
        {
            Name = "HideAndSeek",
            LanguageKey = "GameVoteOptionHideAndSeek",
            Apply = "HideAndSeek"
        }
    },

    SecretModeIdentifier = "mission",
    SecretTraitorProbability = 1,
    SecretDifficulty = 50,
    SecretMissionTypes = {
        "Pirate",
        "Nest",
        "Salvage",
        "SalvageWreck",
        "SalvageCave",
        "SalvageRuin",
        "Mineral",
        "ClearAlienRuins",
        "Beacon",
        "ScanAlienRuins",
        "EliminateThalamus",
        "Monster"
    },
    SecretBlockedPrefixes = {"à-", "#Hide and seek", "Attack&Defend"},
    SecretBlockedTags = {"Shuttle", "HideInMenus"},

    AttackDefendModeIdentifier = "pvp",
    AttackDefendMissionTypes = {"AttackDefenceV2"},
    AttackDefendKeepSecretMissionTypes = true,
    AttackDefendOutpostName = "Random",
    AttackDefendTraitorProbability = 100,

    HideModeIdentifier = "pvp",
    HideTraitorProbability = 0,
    HideMissionTypes = {"HideAndSeekV2"},
    HideKeepSecretMissionTypes = true,
    HideOutpostName = "Random"
}

----- GAMEPLAY -----

config.Codewords = {
    "hull", "tabacco", "nonsense", "fish", "clown", "quartermaster", "fast", "possibility",
	"thalamus", "hungry", "water", "looks", "renegade", "angry", "green", "sink", "rubber",
	"mask", "sweet", "ice", "charybdis", "cult", "secret", "frequency",
	"husk", "rust", "ruins", "red", "boat", "cats", "rats", "blast",
	"tire", "trunk", "weapons", "threshers", "cargo", "method", "monkey"
}

config.AmountCodeWords = 2

config.OptionalTraitors = true        -- players can use !toggletraitor
config.RagdollOnDisconnect = false
config.EnableControlHusk = true     -- EXPERIMENTAL: enable to control husked character after death
config.DeathLogBook = true
config.HideCrewList = true -- EXPERIMENTAL

-- This overrides the game's respawn shuttle, and uses it as a submarine injector, to spawn submarines in game easily. Respawn should still work as expected, but the shuttle submarine file needs to be manually added here.
-- Note: If this is disabled, traitormod will disable all functions related to submarine spawning.
-- Warning: Only respawn shuttles will be used, the option to spawn people directly into the submarine doesnt work.
config.OverrideRespawnSubmarine = false
config.RespawnSubmarineFile = "Content/Submarines/Selkie.sub"
config.RespawnText = "Respawn in %s seconds."
config.RespawnTeam = CharacterTeamType.Team1
config.RespawnOnKillPoints = 0
config.RespawnEnabled = true -- set this to false to disable respawn, respawn shuttle override features will still be active, there just wont be any respawns
config.RespawnTextOnlySpectators = false

-- Allows players that just joined the server to instantly spawn
config.MidRoundSpawn = false

----- POINTS + LIVES -----
config.StartPoints = 5000 -- new players start with this amount of points
config.PermanentPoints = true      -- sets if points and lives will be stored in and loaded from a file
config.RemotePoints = nil
config.RemoteServerAuth = {}

config.PermanentStatistics = true  -- sets if statistics be stored in and loaded from a file
config.MaxLives = 5
config.MinRoundTimeToLooseLives = 180
config.RespawnedPlayersDontLooseLives = true
config.MaxExperienceFromPoints = 500000     -- if not nil, this amount is the maximum experience players gain from stored points (30k = lvl 10 | 38400 = lvl 12)

config.FreeExperience = 250         -- temporary experience given every ExperienceTimer seconds
config.ExperienceTimer = 120 -- passive round skill gain interval in seconds
config.RoundSkillGain = {
    Enabled = true,
    Timer = 240, 
    SecretOnly = true,
    AliveTeam1Only = true,
    AliveRoleMin = 1,
    AliveRoleMax = 10,
    MissingRoleMin = 5,
    MissingRoleMax = 15,
    AliveRoleCap = 40,
    MissingRoleCap = 70,
    Roles = {
        { Job = "captain", Skill = "helm" },
        { Job = "securityofficer", Skill = "weapons" },
        { Job = "mechanic", Skill = "mechanical" },
        { Job = "engineer", Skill = "electrical" },
        { Job = "medicaldoctor", Skill = "medical" },
        { Job = "surgeon", Skill = "surgery" },
    }
}

config.PointsGainedFromSkill = {
    medical = 3,
    surgery = 2,
    weapons = 2,
    mechanical = 1,
    electrical = 1,
    helm = 1,
}

config.PointsLostAfterNoLives = function (x)
    return x * 0.75
end

config.AmountExperienceWithPoints = function (x)
    return x
end

-- Give weight based on the logarithm of experience
-- 100 experience = 4 chance
-- 1000 experience = 6 chance
config.AmountWeightWithPoints = function (x)
    return math.log(x + 10) -- add 1 because log of 0 is -infinity
end

----- GAMEMODE -----
config.GamemodeConfig = {
    Secret = {
        PointshopCategories = {"clown", "traitor", "cultist", "deathspawn", "deathspawnhusk", "deathspawnfriend", "deathtrigerevent", "deathtrigereventevil", "deathtrigereventrandom", "abilities", "surgery", "medical", "security", "wiring", "maintenance", "materials", "ores", "otherresources", "other", "randomize", "ships"},
        EndOnComplete = true,           -- end round everyone but traitors are dead
        EnableRandomEvents = true,
        EndGameDelaySeconds = 60,
        TraitorSelectDelayMin = 120,
        TraitorSelectDelayMax = 150,

        PointsGainedFromHandcuffedTraitors = 3500,
        DistanceToEndOutpostRequired = 8000,

        MissionPoints = {
            Salvage = 1100,
            SalvageWreck = 1250,
            SalvageCave = 1350,
            SalvageRuin = 1500,
            Monster = 1050,
            EliminateThalamus = 2200,
            Cargo = 1000,
            Beacon = 1200,
            Nest = 1700,
            Mineral = 1000,
            Combat = 1400,
            Escort = 1200,
            Pirate = 1300,
            GoTo = 1000,
            OutpostDestroy = 1500,
            OutpostRescue = 1400,
            AbandonedOutpost = 1200,
            AbandonedOutpostMonsters = 1300,
            AbandonedOutpostAssassinate = 1500,
            ["jailbreak"] = 1600,
            ScanAlienRuins = 1600,
            ClearAlienRuins = 2000,
            End = 3500,
            SubVsSubCombat = 1400,
            OutpostCombat = 1400,
            KingOfTheHull = 1500,
            Default = 1000,
        },
        PointsGainedFromCrewMissionsCompleted = 1000,
        LivesGainedFromCrewMissionsCompleted = 1,
        MissionEndAdditionalReward = function ()
            return 0
        end,

        TraitorTypeSelectionMode = "Random", -- Vote | Random
        TraitorTypeChance = {
            Traitor = 50, -- Traitors have 33% chance of being a normal traitor
            Cultist = 50,
            Clown = 50,
        },

        AmountTraitors = function (amountPlayers)
            config.TestMode = false
            if amountPlayers > 18 and math.random() < 0.25 then return 4 end
            if amountPlayers > 12 then return 3 end
            if amountPlayers > 7 then return 2 end            
            if amountPlayers > 3 then return 1 end
            if amountPlayers == 1 then 
                Traitormod.SendMessageEveryone(Traitormod.Language.TestingMode)
                config.TestMode = true
                return 1
            end
            print("Not enough players to start traitor mode.")
            return 0
        end,

        -- 0 = 0% chance
        -- 1 = 100% chance
        TraitorFilter = function (client)
            if client.Character.TeamID ~= CharacterTeamType.Team1 then return 0 end
            if not client.Character.IsHuman then return 0 end
            if client.Character.HasJob("captain") then return 0 end
            if client.Character.HasJob("securityofficer") then return 0 end
            if client.Character.HasJob("medicaldoctor") then return 0.5 end
            if client.Character.HasJob("surgeon") then return 0.5 end
            return 1
        end
    },

    PvP = {
        PointshopCategories = {"clown", "traitor", "cultist", "deathspawn", "deathspawnhusk", "deathspawnfriend", "deathtrigerevent", "deathtrigereventevil", "deathtrigereventrandom", "surgery", "medical", "security", "wiring", "maintenance", "materials", "ores", "otherresources", "other", "ships"},
        EnableRandomEvents = false, -- most events are coded to only affect the main submarine
        WinningPoints = 1000,
        WinningDeadPoints = 500,
        MinimumPlayersForPoints = 4,
        ShowSonar = true,
        IdCardAllAccess = true,
        CrossTeamCommunication = true,
        BannedItems = {"coilgunammoboxexplosive", "nuclearshell"}
    },

    AttackDefendV2 = {
        PointshopCategories = {"spawnBlue", "spawnRed"},
        DefendTime = 15,
        DefendRespawn = 60,
        AttackRespawn = 70,
        WinningPointsTeam1 = 2000,
        DefaultClassTeam1 = "coalition_soldier_1",
        WinningPointsTeam2 = 1000,
        DefaultClassTeam2 = "separatists_soldier_1",
    },

    HideAndSeekV2 = {
        PointshopCategories = {"hideBlue", "hideRed"},
        StartDelayMinutes = 1,
        RoundDurationMinutes = 6,
        ClassSelectionTimeoutMinutes = 3,
        ReconnectGraceSeconds = 60,
        WinningPointsBlue = 2000,
        WinningPointsRed = 2000,
    },
}

config.RoleConfig = {
    Crew = {
        AvailableObjectives = {
            ["captain"] = {"KillLargeMonsters", "FinishRoundFast", "SecurityTeamSurvival"},
            ["engineer"] = {"RepairElectrical", "RepairMechanical", "KillSmallMonsters"},
            ["mechanic"] = {"RepairMechanical", "RepairHull", "KillSmallMonsters"},
            ["securityofficer"] = {"KillLargeMonsters", "KillSmallMonsters"},
            ["medicaldoctor"] = {"HealCharacters", "KillSmallMonsters"},
            ["assistant"] = {"RepairElectrical", "RepairMechanical", "KillPets"},
			["surgeon"] = {"HealCharacters", "KillSmallMonsters"},
        }
    },

    Cultist = {
        SubObjectives = {"Assassinate", "Kidnap", "TurnHusk", "DestroyCaly"},
        MinSubObjectives = 2,
        MaxSubObjectives = 3,

        NextObjectiveDelayMin = 30,
        NextObjectiveDelayMax = 60,

        TraitorBroadcast = true,           -- traitors can broadcast to other traitors using !tc
        TraitorBroadcastHearable = false,  -- if true, !tc will be hearable in the vicinity via local chat
        TraitorDm = true,                  -- traitors can send direct messages to other players using !tdm

        -- Names, None
        TraitorMethodCommunication = "Names",

        SelectBotsAsTargets = true,
        SelectPiratesAsTargets = false,
    },

    HuskServant = {
        TraitorBroadcast = true,
    },

    Traitor = {
        SubObjectives = {"StealCaptainID", "Survive", "Kidnap", "PoisonCaptain"},
        MinSubObjectives = 2,
        MaxSubObjectives = 3,

        NextObjectiveDelayMin = 30,
        NextObjectiveDelayMax = 60,

        TraitorBroadcast = true,           -- traitors can broadcast to other traitors using !tc
        TraitorBroadcastHearable = false,  -- if true, !tc will be hearable in the vicinity via local chat
        TraitorDm = true,                  -- traitors can send direct messages to other players using !tdm

        -- Names, Codewords, None
        TraitorMethodCommunication = "Names",

        SelectBotsAsTargets = true,
        SelectPiratesAsTargets = false,
        SelectUniqueTargets = true,     -- every traitor target can only be chosen once per traitor (respawn+false -> no end)
        PointsPerAssassination = 100,
    },

    Clown = {
        SubObjectives = {"BananaSlip", "SuffocateCrew", "AssassinateDrunk", "GrowMudraptors", "DetonateLocation", "Survive"},
        MinSubObjectives = 3,
        MaxSubObjectives = 3,

        NextObjectiveDelayMin = 30,
        NextObjectiveDelayMax = 60,

        TraitorBroadcast = true,           -- traitors can broadcast to other traitors using !tc
        TraitorBroadcastHearable = false,  -- if true, !tc will be hearable in the vicinity via local chat
        TraitorDm = true,                  -- traitors can send direct messages to other players using !tdm

        -- Names, None
        TraitorMethodCommunication = "Names",

        SelectBotsAsTargets = true,
        SelectPiratesAsTargets = false,
    },
}

config.ObjectiveConfig = {
    Assassinate = {
        AmountPoints = 600,
    },

    Survive = {
        AlwaysActive = true,
        AmountPoints = 500,
        AmountLives = 1,
    },

    StealCaptainID = {
        AmountPoints = 1300,
    },

    Kidnap = {
        AmountPoints = 2500,
        Seconds = 100,
    },

    PoisonCaptain = {
        AmountPoints = 1600,
    },

    Husk = {
        AmountPoints = 800,
    },

    TurnHusk = {
        AmountPoints = 500,
        AmountLives = 1,
    },

    SuffocateCrew = {
        AmountPoints = 900,
        RequiredLowOxygenSeconds = 4,
        SuffocationKillWindowSeconds = 20,
        SevereOxygenThreshold = 15,
        LowOxygenAfflictionThreshold = 35,
        AdditionalLowOxygenAfflictions = {"oxygenlow", "hypoxemia", "cerebralhypoxia", "asphyxia"},
    },

    HealCharacters = {
        AmountPoints = 400,
        Amount = 500,
        RecentTreatmentAttributionSeconds = 12,
        DedupWindowSeconds = 0.05,
        MinimumReportedHeal = 0.5,
    },

    DestroyCaly = {

        AmountPoints = 500,
    },

    DetonateLocation = {
        AmountPoints = 1200,
        AmountPointsWithVictim = 1800,
        RequireVictimChance = 0.5,
        MaxVictimDistance = 500,
        DetonatorIdentifiers = {"detonator", "timeddetonator", "artmod_detonator"},
    },
}

----- EVENTS -----
config.RandomEventConfig = {
    Events = {
        dofile(Traitormod.Path .. "/Lua/config/randomevents/superballastflora.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/maintenancetoolsdelivery.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/medicaldelivery.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/ammodelivery.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abysshelp.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/emergencyteam.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/shadymission.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/prisoner.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/ventcreatures.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/clowncratesurprise.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/weakballastflora.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/wreckrescue.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/beaconrescue.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/cultist/oxygengenhusk.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/clown/randomlights.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/clown/clownmagic.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/traitor/lightsoff.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/traitor/communicationsoffline.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/traitor/reactorshutdown.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/traitor/supercapacitorfailure.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/traitor/junctionboxoverload.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/traitor/oxygengenpoison.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/traitor/oxygensufforin.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/traitor/oxygenparalyzant.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/traitor/oxygenmorbusine.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/sabotage/traitor/oxygencyanide.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/captainhelmboost.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/securitymindsense.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/securityturretcoilgun.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/securityturretchaingun.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/securityturretflakcannon.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/securityturretpulselaser.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/securityturretdoublecoilgun.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/securityturretrailgun.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/mechanicmechanicalrepair.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/mechanichullrepair.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/mechanicskillboost.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/engineerelectricalrepair.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/engineerskillboost.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/medicskillboost.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/abilities/surgeonskillboost.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/pirate/outpostpirateattack.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/pirate/piratecrew.lua"),
				dofile(Traitormod.Path .. "/Lua/config/randomevents/pirate/hiddenpirate.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/pirate/wreckpirate.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/pirate/beaconpirate.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/repair/electricalfixdischarge.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/repair/fixhull.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/repair/fullfixshull.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/repair/fullelectricalfixdischarge.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/break/breackelectrical.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/break/breackhull.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/break/killelectrical.lua"),
        dofile(Traitormod.Path .. "/Lua/config/randomevents/break/killhull.lua"),
    }
}

config.PointShopConfig = {
    Enabled = true,
    DeathTimeoutTime = 60,
    DeathSpawnRefundAtEndRound = true,
    ItemCategories = {
        dofile(Traitormod.Path .. "/Lua/config/pointshop/security.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/maintenance.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/materials.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/medical.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/ores.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/other.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/wiring.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/ships.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/surgery.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/otherresources.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/randomize.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/abilities.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/traitors/clown.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/traitors/cultist.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/traitors/traitor.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/attackdefend/spawnBlue.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/attackdefend/spawnRed.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/hideandseek/hideBlue.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/hideandseek/hideRed.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/deathspawns/deathspawn.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/deathspawns/deathspawnhusk.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/deathspawns/deathspawnfriend.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/events/deathtrigerevent.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/events/deathtrigereventevil.lua"),
        dofile(Traitormod.Path .. "/Lua/config/pointshop/events/deathtrigereventrandom.lua"),
    }
}

config.UPCPirateConfig = {
    EliminateCrewReward = 2500,
    CaptureReward = 1500,
    CaptureDurationSeconds = 60,
    EndRoundDelaySeconds = 5,
}

config.MonsterBeaconConfig = {
    Enabled = true,
    ActivationTime = 30,
    GhostRoleChance = 0.3,
    SpawnWallDistance = 250,
    SpawnJitter = 150,
    UseOptionalHuskPools = true,
    Pools = {
        {Name = "MudraptorPack", Creatures = {"mudraptor", "mudraptor", "mudraptor", "mudraptor", "mudraptor"}},
        {Name = "TigerthresherPack", Creatures = {"Tigerthresher", "Tigerthresher", "Tigerthresher", "mudraptor"}},
        {Name = "VeteranMudraptorPack", Creatures = {"Mudraptor_veteran", "Mudraptor_veteran", "mudraptor"}},
        {Name = "CrawlerPack", Creatures = {"crawler", "crawler", "crawler", "crawler", "crawler", "crawler"}},
        {Name = "BonethresherPack", Creatures = {"Bonethresher", "Tigerthresher", "Tigerthresher"}},
    },
    OptionalHuskPools = {
        {Name = "CrawlerHuskPack", Creatures = {"Crawlerhusk", "Crawlerhusk", "Crawlerhusk", "Crawlerhusk", "Crawlerhusk", "Crawlerhusk"}},
        {Name = "MudraptorHuskPack", Creatures = {"Mudraptormispawnhusk", "Mudraptormispawnhusk", "Mudraptormispawnhusk", "Mudraptormispawnhusk", "Mudraptormispawnhusk"}},
        {Name = "TigerthresherHuskPack", Creatures = {"Tigerthresherhusk", "Tigerthresherhusk", "Tigerthresherhusk", "Mudraptormispawnhusk"}},
        {Name = "BonethresherHuskPack", Creatures = {"Bonethresherhusk", "Tigerthresherhusk", "Tigerthresherhusk"}},
    }
}

config.GhostRoleConfig = {
    Enabled = true,
    MenuPageSize = 10,
    DeadRoleLifetimeSeconds = 180,
    DisconnectedCharacterDelaySeconds = 180,
    Groups = {
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/ventcreatures.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/clowncrate.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/rescue.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/emergency.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/prisoner.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/pirates/beacon.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/pirates/wreck.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/pirates/hidden.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/pirates/crew.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/pirates/mission.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/monsterbeacon.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/misc.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/pointshop.lua"),
        dofile(Traitormod.Path .. "/Lua/config/ghostrole/system.lua"),
    }
}

return config
