-- Generated by VoidTraitorPackBuilder. Do not edit.
local packPath = table.pack(...)[1]

-- Keep LuaCs module paths belonging to every other enabled Lua mod.
local modulePaths = {}
for i = 1, #package.path do
    modulePaths[#modulePaths + 1] = package.path[i]
end

local function addModulePath(path)
    for i = 1, #modulePaths do
        if modulePaths[i] == path then return end
    end
    modulePaths[#modulePaths + 1] = path
end

addModulePath(packPath .. "/Lua/?.lua")
addModulePath(packPath .. "/NT Surgery Plus/Lua/?.lua")
addModulePath(packPath .. "/NT Cybernetics Enhanced Forked/Lua/?.lua")
addModulePath(packPath .. "/NT Nanite Integration/Lua/?.lua")
setmodulepaths(modulePaths)
package.path = modulePaths

local function runBundled(modFolder, scriptPath)
    local modPath = packPath .. "/" .. modFolder
    local chunk, loadError = loadfile(modPath .. "/" .. scriptPath)
    if chunk == nil then error(loadError, 0) end

    local markerName = "__VTPACK_BUNDLED_AUTORUN"
    local previousMarker = rawget(_G, markerName)
    _G[markerName] = modFolder .. "/" .. scriptPath
    local ok, runError = pcall(chunk, modPath)
    _G[markerName] = previousMarker
    if not ok then error(runError, 0) end
end

runBundled("NT Surgery Plus", "Lua/Autorun/init.lua")
runBundled("NT Cybernetics Enhanced Forked", "Lua/Autorun/init.lua")
runBundled("NT Nanite Integration", "Lua/Autorun/init.lua")
